# CMake generated Testfile for 
# Source directory: /Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz
# Build directory: /Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(usda-parser-unit-test "python3" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/tests/usda/unit-runner.py" "--app" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native/test_tinyusdz" "--basedir" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/tests/usda")
set_tests_properties(usda-parser-unit-test PROPERTIES  _BACKTRACE_TRIPLES "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;1808;add_test;/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;0;")
add_test(usda-roundtrip-test "python3" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/tests/usda/roundtrip-runner.py" "--app" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native/usda_roundtrip" "--basedir" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/tests/usda")
set_tests_properties(usda-roundtrip-test PROPERTIES  _BACKTRACE_TRIPLES "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;1828;add_test;/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;0;")
add_test(usdc-roundtrip-test "python3" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/tests/usda/usdc-roundtrip-runner.py" "--app" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native/usdc_roundtrip" "--basedir" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/tests/usda")
set_tests_properties(usdc-roundtrip-test PROPERTIES  _BACKTRACE_TRIPLES "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;1848;add_test;/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;0;")
add_test(usdc-parser-unit-test "python3" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/tests/usdc/unit-runner.py" "--app" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native/test_tinyusdz" "--basedir" "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/tests/usdc")
set_tests_properties(usdc-parser-unit-test PROPERTIES  _BACKTRACE_TRIPLES "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;1859;add_test;/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;0;")
add_test(feat-mtlx-parse "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native/feat-mtlx-parse")
set_tests_properties(feat-mtlx-parse PROPERTIES  WORKING_DIRECTORY "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz" _BACKTRACE_TRIPLES "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;1874;add_test;/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;0;")
add_test(feat-mtlx-import "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native/feat-mtlx-import")
set_tests_properties(feat-mtlx-import PROPERTIES  _BACKTRACE_TRIPLES "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;1880;add_test;/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;0;")
add_test(feat-mtlx-export "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native/feat-mtlx-export")
set_tests_properties(feat-mtlx-export PROPERTIES  _BACKTRACE_TRIPLES "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;1885;add_test;/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;0;")
add_test(feat-variant-converter "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native/feat-variant-converter")
set_tests_properties(feat-variant-converter PROPERTIES  WORKING_DIRECTORY "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz" _BACKTRACE_TRIPLES "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;1891;add_test;/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;0;")
add_test(feat-variant-applier "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native/feat-variant-applier")
set_tests_properties(feat-variant-applier PROPERTIES  WORKING_DIRECTORY "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz" _BACKTRACE_TRIPLES "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;1897;add_test;/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;0;")
add_test(feat-mtlx-grouped-params "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native/feat-mtlx-grouped-params")
set_tests_properties(feat-mtlx-grouped-params PROPERTIES  _BACKTRACE_TRIPLES "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;1905;add_test;/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;0;")
add_test(bench-parse-opt "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/build_native/bench-parse-opt")
set_tests_properties(bench-parse-opt PROPERTIES  LABELS "benchmark" _BACKTRACE_TRIPLES "/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;1915;add_test;/Users/gabehollander/Documents/lightcraft/lightcraft/tinyusdz/CMakeLists.txt;0;")
subdirs("path-sort-and-encode-crate")
subdirs("examples/tusdcat")
subdirs("examples/tydra_api")
subdirs("examples/tydra_to_renderscene")
subdirs("examples/variant-lister")
subdirs("examples/variant-analyzer")
subdirs("examples/usddiff")
subdirs("examples/api_tutorial")
subdirs("examples/file_format")
subdirs("examples/asset_resolution")
subdirs("examples/progressive_composition")
subdirs("examples/save_usda")
subdirs("tests/unit")
subdirs("tests/decompress-int")
subdirs("tests/pprint")
